CIS-213 fix auto append zero
dintecom/date-time-picker pull request #5
Opened 2023-01-18 17:14 UTC by AlexeyShDintecom

https://dintecom.atlassian.net/browse/CIS-213

2023-01-20 00:23 UTC, ArtemDintecom requested changes

2023-01-20 00:23 UTC, ArtemDintecom commented on projects/picker/src/lib/date-time/timer-box.component.ts
> +  private printMode: boolean = false;
```suggestion
  private editMode: boolean = false;
```
или inputMode

2023-01-20 00:23 UTC, ArtemDintecom commented on projects/picker/src/lib/date-time/timer-box.component.ts
> -    this.inputStreamSub = this.inputStream.pipe(debounceTime(500)).subscribe((val: string) => {
Почему debounceTime не нужен?

2023-01-20 12:37 UTC, AlexeyShDintecom commented on projects/picker/src/lib/date-time/timer-box.component.ts
> -    this.inputStreamSub = this.inputStream.pipe(debounceTime(500)).subscribe((val: string) => {
Мы же с тобой вместе сидели, и ты сказал что почему полсекунды и вообще зачем он, не нужен он здесь
Поэтому убрал, вернуть?

2023-01-20 15:53 UTC, ArtemDintecom approved these changes

2023-01-20 15:54 UTC, AlexeyShDintecom commented
Там нашел еще один баг, сейчас исправляю

2023-01-23 15:26 UTC, AlexeyShDintecom commented
@ArtemDintecom Во втором коммите сделал чтобы менялся час, норм?
Попроще не вышло, там вся логика изменения часов/минут/секунд поменялась

2023-01-24 12:20 UTC, ArtemDintecom approved these changes

2023-01-24 12:20 UTC, merged